/**
 * ClientView.java
 * Class ClientView is our class for implementing the view in the MVC architecture for the client side.
 * 
 *  @version   $Id: ServerView.java,v 1.0 2013/11/26 11:20pm $
 * 
 * @author Pavan Kumar Pallerla
 * @author Eric Fortunato
 * 
 *
 */

import java.awt.event.ActionListener;

import javax.swing.*;


public class ClientView extends JFrame{

	public ClientView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        tossButton = new javax.swing.JButton();
        winnerTextField = new javax.swing.JTextField();
        selectSideLabel = new javax.swing.JLabel();
        winnerLabel = new javax.swing.JLabel();
        headsRadioButton = new javax.swing.JRadioButton();
        tailsRadioButton = new javax.swing.JRadioButton();
        playerLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tossButton.setText("Toss");

        selectSideLabel.setText("Select the side");

        winnerLabel.setText("Winner");

        buttonGroup.add(headsRadioButton);
        headsRadioButton.setText("Heads");

        buttonGroup.add(tailsRadioButton);
        tailsRadioButton.setText("Tails");

        playerLabel.setText("Player - I");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(selectSideLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(headsRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tailsRadioButton)
                        .addGap(0, 58, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(winnerLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(tossButton)
                        .addGap(76, 76, 76)
                        .addComponent(winnerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(224, 224, 224))
            .addGroup(layout.createSequentialGroup()
                .addGap(218, 218, 218)
                .addComponent(playerLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(playerLabel)
                .addGap(32, 32, 32)
                .addComponent(selectSideLabel)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(headsRadioButton)
                            .addComponent(tailsRadioButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(tossButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addComponent(winnerLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(winnerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(190, 190, 190))
        );

        pack();
    }// </editor-fold>
    
    /**
     * returns 0 if heads is selected and 1 if tails is selected
     */
    public int getSelectedRadioButton () {
    	int buttonValue = 2;
    	if (headsRadioButton.isSelected()) {
    		buttonValue =  0;
    	} else if (tailsRadioButton.isSelected()){
    		buttonValue = 1;
    	}
    	return buttonValue;
    }
    
    /**
     * sets winner TextField
     * @param winner int value of the winner
     */
    public void setWinner(int winner) {
    	if (winner == 0) {
    		winnerTextField.setText("Player - I");
    	} else {
    		winnerTextField.setText("Player - II");
    	}
    }
    
    /**
     * listener for toss button
     * @param listenerForTossButton 
     */
    public void addTossListener (ActionListener listenerForTossButton) {
    	tossButton.addActionListener(listenerForTossButton);
    }

    // Variables declaration - do not modify                     
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JRadioButton headsRadioButton;
    private javax.swing.JLabel playerLabel;
    private javax.swing.JLabel selectSideLabel;
    private javax.swing.JRadioButton tailsRadioButton;
    private javax.swing.JButton tossButton;
    private javax.swing.JLabel winnerLabel;
    private javax.swing.JTextField winnerTextField;
}
